sudo: required
services:
  - docker

before_install:
  - docker build -t shaymal/docker-multi-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shaymal/docker-multi-react npm run test -- --coverage

